apply plugin: 'com.github.johnrengelman.shadow'

architectury {
    platformSetupLoomIde()
    forge()
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

dependencies {
    forge "net.minecraftforge:forge:${rootProject.forge_version}"

    modImplementation "dev.architectury:architectury-forge:${rootProject.architectury_api_version}"
    modImplementation "software.bernie.geckolib:geckolib-forge-1.20.1:${rootProject.geckolib_version}"

    // modImplementation "curse.maven:untitled-duck-mod-PROJECTID:FORGE-FILEID"

    common(project(path: ":common", configuration: "namedElements")) { transitive = false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) { transitive = false }
}

tasks.named("processResources") {
    inputs.property "mod_version", rootProject.mod_version

    filesMatching("META-INF/mods.toml") {
        expand "version": rootProject.mod_version
    }
}

tasks.named("shadowJar", com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar) {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

tasks.named("remapJar") {
    inputFile = shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = null
}

tasks.named("jar") {
    archiveClassifier = "dev"
}

tasks.named("sourcesJar") {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) { skip() }
}