architectury {
    common(rootProject.enabled_platforms.split(","))
}

dependencies {
    modImplementation "dev.architectury:architectury:${rootProject.architectury_api_version}"
    modCompileOnly "software.bernie.geckolib:geckolib-fabric-${rootProject.minecraft_version}:${rootProject.geckolib_version}"

    // Untitled Duck Mod — use the Fabric jar for common compilation
    // modCompileOnly "curse.maven:untitled-duck-mod-PROJECTID:FABRIC-FILEID"
}
