modLoader="javafml"
loaderVersion="[1,)"
license="All Rights Reserved"

[[mods]]
modId="duckarmor"
version="1.0.0"
displayName="Duck Armor"
description="Allows you to put armor on ducks and geese!"

[[dependencies.duckarmor]]
    modId="neoforge"
    mandatory=true
    versionRange="[20.6,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.duckarmor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.6,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.duckarmor]]
    modId="architectury"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies.duckarmor]]
    modId="geckolib"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies.duckarmor]]
    modId="untitledduckmod"
    mandatory=false
    versionRange="*"
    ordering="NONE"
    side="BOTH"
